<Project Sdk="Microsoft.NET.Sdk">
    
  <PropertyGroup>
    <Description>Helpers for sending emails.</Description>
    <AssemblyName>Dotnet$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Dotnets$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModularPipelines\ModularPipelines.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" />
    </ItemGroup>

</Project>
