name: Renovate

on:
  schedule:
    - cron: "0 */1 * * *"

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Renovate Bot GitHub Action
      # You may pin to the exact commit or the version.
      # uses: renovatebot/github-action@aa150c86873c3e1326734d9c1390064fbc646148
      uses: renovatebot/github-action@v36.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
          RENOVATE_AUTODISCOVER: true
